# Generated by Django 4.2.6 on 2024-05-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicflot', '0005_rename_qiestion_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.CharField(max_length=100, null=True, verbose_name='Ответ 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.CharField(max_length=100, null=True, verbose_name='Ответ 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.CharField(max_length=100, null=True, verbose_name='Ответ 4'),
        ),
    ]
