# Generated by Django 4.2.6 on 2024-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicflot', '0006_alter_question_answer_2_alter_question_answer_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winner',
            name='school',
            field=models.CharField(max_length=30, verbose_name='Школа №'),
        ),
    ]
