# Generated by Django 4.2.6 on 2024-05-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicflot', '0007_winner_created_alter_winner_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='created',
        ),
    ]
