# Generated by Django 4.2.6 on 2024-05-13 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magicflot', '0008_remove_winner_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
