# Generated by Django 4.1.13 on 2024-05-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWorkCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('art_category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['art_category'],
            },
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trumb', models.ImageField(upload_to='trumb/', verbose_name='Миниатюра')),
                ('img', models.ImageField(upload_to='gallery/', verbose_name='Путь к картинке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Аннотация работы')),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trumb', to='gallery.artworkcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]
